CREATE TABLE `tb_op_order` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '????ID',
  `ORDER_ID` varchar(100) NOT NULL COMMENT '????ID',
  `PLAT_CD` varchar(100) NOT NULL COMMENT 'ƽ̨',
  `PLAT_NAME` varchar(50) NOT NULL COMMENT 'ƽ̨????',
  `SHOP_ID` varchar(50) DEFAULT NULL COMMENT '????ID',
  `ORDER_UPDATE_TIME` datetime DEFAULT NULL COMMENT '?????޸?ʱ??',
  `ORDER_TIME` datetime DEFAULT NULL COMMENT '?µ?ʱ??',
  `ORDER_PAY_TIME` datetime DEFAULT NULL COMMENT '֧??ʱ??',
  `ORDER_CREATE_TIME` datetime DEFAULT NULL COMMENT '????????ʱ??',
  `USER_ID` varchar(50) DEFAULT NULL COMMENT '????ID',
  `USER_NAME` varchar(200) DEFAULT NULL,
  `USER_EMAIL` varchar(200) DEFAULT NULL COMMENT '????????',
  `ADDRESS_USER_NAME` varchar(160) DEFAULT NULL COMMENT '用户名',
  `ADDRESS_USER_PHONE` varchar(100) DEFAULT NULL COMMENT '?ջ?????ϵ??ʽ',
  `ADDRESS_USER_COUNTRY` varchar(100) DEFAULT NULL,
  `ADDRESS_USER_COUNTRY_ID` varchar(80) DEFAULT NULL COMMENT '收货人国家ID',
  `ADDRESS_USER_COUNTRY_CODE` varchar(10) DEFAULT NULL COMMENT '?ջ??˹??Ҵ???',
  `ADDRESS_USER_COUNTRY_EDIT` varchar(100) DEFAULT NULL COMMENT '收件人国家编辑值',
  `ADDRESS_USER_CITY` varchar(100) DEFAULT NULL,
  `ADDRESS_USER_PROVINCES` varchar(200) DEFAULT NULL,
  `ADDRESS_USER_REGION` varchar(200) DEFAULT NULL,
  `ADDRESS_USER_ADDRESS1` varchar(500) DEFAULT NULL COMMENT '?ջ???ַ1',
  `ADDRESS_USER_ADDRESS2` varchar(500) DEFAULT NULL COMMENT '?ջ???ַ2',
  `ADDRESS_USER_ADDRESS3` varchar(500) DEFAULT NULL COMMENT '?ջ???ַ3',
  `ADDRESS_USER_ADDRESS4` varchar(500) DEFAULT NULL COMMENT '?ջ???ַ4',
  `ADDRESS_USER_ADDRESS5` varchar(500) DEFAULT NULL COMMENT '?ջ???ַ5',
  `ADDRESS_USER_POST_CODE` varchar(128) DEFAULT NULL,
  `PAY_CURRENCY` varchar(10) DEFAULT NULL COMMENT '֧??????',
  `PAY_ITEM_PRICE` decimal(10,2) DEFAULT NULL,
  `PAY_TOTAL_PRICE` decimal(10,2) DEFAULT NULL,
  `PAY_SHIPING_PRICE` decimal(10,2) DEFAULT NULL,
  `PAY_VOUCHER_AMOUNT` decimal(10,2) DEFAULT NULL,
  `CHILDREN_VOUCHER_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '子单分配的优惠金额',
  `PAY_PRICE` decimal(10,2) DEFAULT NULL,
  `PAY_WRAPPER_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '包装费用-Amazon',
  `PAY_INSTALMENT_SERVICE_AMOUNT` decimal(10,2) DEFAULT NULL COMMENT '分期手续费-Cdiscount',
  `PAY_METHOD` varchar(200) DEFAULT NULL,
  `PAY_TRANSACTION_ID` varchar(50) DEFAULT NULL COMMENT '֧???ţ?֧??ID??',
  `SHIPPING_TYPE` varchar(50) DEFAULT NULL,
  `SHIPPING_DELIVERY_COMPANY` varchar(50) DEFAULT NULL COMMENT '???͹?˾',
  `SHIPPING_DELIVERY_COMPANY_CD` varchar(10) DEFAULT NULL COMMENT '运送公司code',
  `SHIPPING_TRACKING_CODE` varchar(50) DEFAULT NULL COMMENT '????????',
  `SHIPPING_MSG` varchar(1000) DEFAULT NULL,
  `CRAWLER_DATE` datetime DEFAULT NULL COMMENT '??ȡʱ??',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `ORDER_STATUS` varchar(50) DEFAULT NULL COMMENT '????????',
  `ORDER_NUMBER` varchar(512) DEFAULT NULL COMMENT 'ebay发货参数,多商品订单中间用逗号隔开',
  `SITE` varchar(200) DEFAULT NULL,
  `ADDRESS_USER_ADDRESS_MSG` varchar(200) DEFAULT NULL,
  `BWC_ORDER_STATUS` varchar(12) DEFAULT NULL,
  `PAY_SETTLE_PRICE` decimal(10,2) DEFAULT NULL COMMENT '结算价格',
  `PAY_SETTLE_PRICE_DOLLAR` decimal(10,2) DEFAULT NULL COMMENT '美元结算价-ALL',
  `BWC_USER_ID` varchar(50) DEFAULT NULL COMMENT '帮5采userID',
  `PACK_NO` varchar(20) DEFAULT NULL COMMENT '购物车代表号码(Qoo10)',
  `PACKING_NO` varchar(20) DEFAULT NULL COMMENT '包装号码(Qoo10)',
  `RELATED_ORDER` text COMMENT '订购号码(Qoo10)',
  `SELLER_DELIVERY_NO` varchar(20) DEFAULT NULL COMMENT '运送号码(Qoo10)',
  `B5C_ORDER_NO` varchar(20) DEFAULT NULL COMMENT 'B5C订单ID',
  `B5C_ACCOUNT_ID` varchar(20) DEFAULT NULL COMMENT '帮我采订单所对应用户ID',
  `SHORT_SUPPLY` int(1) DEFAULT '0' COMMENT '是否超卖0-否;1-是',
  `B5C_ORDER_DES_COUNT` int(11) DEFAULT '0' COMMENT '生成帮我采订单操作数量',
  `SHIPPING_TIME` datetime DEFAULT NULL COMMENT '发货时间(平台发货时间)',
  `REFUND_STAT_CD` varchar(21) DEFAULT 'N001080500' COMMENT '退款状态码（退款待处理 N001080100，退款申请通过 N001080200，退款成功 N001080300，退款拒绝 N001080400）',
  `RECEIVER_TEL` varchar(100) DEFAULT NULL COMMENT '接受人固定电话-Q10',
  `BUYER_TEL` varchar(50) DEFAULT NULL COMMENT '买家固定电话号码',
  `BUYER_MOBILE` varchar(50) DEFAULT NULL COMMENT '买家手机号码',
  `REMARK_STAT_CD` tinyint(4) DEFAULT '0' COMMENT '备注状态0未备注，1已备注',
  `ORDER_STATUS1` varchar(50) DEFAULT NULL COMMENT '订单状态',
  `FAIL_TIMES` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '订单拉取失败次数',
  `REMARK_MSG` varchar(1000) DEFAULT '' COMMENT '备注信息',
  `CREATE_USER` varchar(20) DEFAULT NULL COMMENT '创建人',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '上传文件名称',
  `TARIFF` decimal(12,2) DEFAULT NULL COMMENT '税费',
  `SHIPPING_TAX` decimal(12,2) DEFAULT NULL COMMENT '运费税费-AMAZON',
  `PROMOTION_DISCOUNT_TAX` decimal(12,2) DEFAULT NULL COMMENT '优惠费税费-AMAZON',
  `SHIPPING_DISCOUNT_TAX` decimal(12,2) DEFAULT NULL COMMENT '运费折扣税费-AMAZON',
  `GIFT_WRAP_TAX` decimal(12,2) DEFAULT NULL COMMENT '包装费税费-AMAZON',
  `THIRD_DELIVER_STATUS` tinyint(1) DEFAULT '0' COMMENT '第三方平台发货状态(1:成功, 0: 否,2待/进行中,3失败)',
  `STORE_ID` smallint(3) NOT NULL COMMENT '店铺标识,同一平台下可以有多个店铺(tb_ms_store.id)',
  `ORDER_NO` varchar(100) DEFAULT NULL COMMENT '订单编号',
  `SHOP_STORE_MAPPING` varchar(255) DEFAULT NULL COMMENT '与store表shop_id字段映射',
  `WAREHOUSE` varchar(10) DEFAULT NULL COMMENT '仓库',
  `SEND_ORD_MSG` varchar(200) DEFAULT NULL COMMENT '派单失败原因',
  `SEND_ORD_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派单时间',
  `ORDER_SEQUENCE` varchar(200) DEFAULT '' COMMENT '11ST订单顺序 发货时使用',
  `b5c_logistics_cd` varchar(32) DEFAULT NULL COMMENT 'b5c物流公司编码',
  `SEND_ORD_STATUS` varchar(50) DEFAULT 'N001820100' COMMENT '派单状态',
  `UPDATE_USER_LAST` varchar(80) DEFAULT NULL COMMENT '最后SKU更新用户名',
  `SHIPPING_NUMBER` varchar(11) DEFAULT '' COMMENT '11ST发货号(非运单号,功发货接口使用)',
  `MPS` varchar(255) DEFAULT NULL COMMENT 'gapp同步订单bi字段',
  `SELLER_ID` varchar(50) DEFAULT NULL COMMENT '卖家ID',
  `SOURCE` varchar(255) DEFAULT NULL COMMENT '订单来源',
  `FIND_ORDER_JSON` text COMMENT '推荐派单json',
  `FIND_ORDER_ERROR_TYPE` varchar(13) DEFAULT NULL COMMENT '推荐派单异常错误码(N002050开头)',
  `FIND_ORDER_INVOKE_TIMES` int(11) NOT NULL DEFAULT '0' COMMENT '派单推荐接口调用次数',
  `FIND_ORDER_FAIL_MSG` varchar(100) DEFAULT NULL COMMENT '推荐派单异常错误信息',
  `FIND_ORDER_TIME` datetime DEFAULT NULL COMMENT '推荐派单时间',
  `PARENT_ORDER_ID` varchar(100) DEFAULT NULL COMMENT '父订单id',
  `CHILD_ORDER_ID` varchar(255) DEFAULT NULL COMMENT '子订单id',
  `COUPONS_ID` varchar(500) DEFAULT NULL COMMENT '优惠券ID，多个以逗号隔开',
  `CANAL_BATCH_VAL` int(10) NOT NULL DEFAULT '0' COMMENT 'canal更新标识',
  `receiver_cust_id` int(11) DEFAULT NULL COMMENT '收件客户ID',
  `logistic_cd` varchar(12) DEFAULT NULL COMMENT '物流公司code',
  `logistic_model_id` int(11) DEFAULT NULL COMMENT '物流方式ID',
  `PAY_TOTAL_PRICE_DOLLAR` decimal(10,2) DEFAULT NULL COMMENT '支付总金额（美元）',
  `SEND_FREIGHT` decimal(10,2) DEFAULT NULL COMMENT '预派单运费',
  `SEND_ORD_TYPE` int(1) DEFAULT '0' COMMENT '是否一键通过(0-是;1-否;)',
  `SURFACE_WAY_GET_CD` varchar(12) DEFAULT NULL COMMENT '面单获取方式(码表以N00201开头)',
  `ADVANCE_ORD_TYPE_CD` varchar(12) DEFAULT NULL COMMENT '预派单异常错误码(N002050开头)',
  `ADVANCE_ORD_MSG` varchar(100) DEFAULT NULL COMMENT '预派单异常错误信息',
  `ADVANCE_ORD_TIME` datetime DEFAULT NULL COMMENT '预派单时间',
  `ADVANCE_ORD_USER` varchar(100) DEFAULT NULL COMMENT '预派单用户登录名',
  `SEND_ORD_TYPE_CD` varchar(12) DEFAULT NULL COMMENT '派单异常错误码(N002030开头)',
  `SEND_ORD_USER` varchar(100) DEFAULT NULL COMMENT '派单用户登录账户',
  `LOGISTICS_SINGLE_STATU_CD` varchar(12) DEFAULT 'N002080100' COMMENT '面单获取状态code(N00208开头)',
  `LOGISTICS_SINGLE_UP_TIME` datetime DEFAULT NULL COMMENT '面单操作更新时间',
  `LOGISTICS_SINGLE_ERROR_MSG` longtext,
  `SEND_ORD_ERROR_STATUS_CD` varchar(80) DEFAULT 'N002030100' COMMENT '派单失败状态CODE（N00203）',
  `voucher_code` varchar(255) DEFAULT NULL COMMENT '支票CODE',
  `BUYER_USER_IDENTITY_CARD` varchar(100) DEFAULT NULL COMMENT '买家身份证',
  `ADDRESS_USER_IDENTITY_CARD` varchar(100) DEFAULT NULL COMMENT '收件人身份证',
  `SEARCH_BACK` int(2) DEFAULT '0' COMMENT '处理数据所用列',
  `has_default_warehouse` int(1) DEFAULT '0' COMMENT '0-没有默认仓库,1-有默认仓库(拉单时填充)',
  `default_warehouse_logistics` varchar(1023) DEFAULT NULL COMMENT '拉单时第三方提供用于匹配仓库物流的值',
  `is_mark` int(11) DEFAULT '0' COMMENT '标记订单',
  `freight_type` varchar(11) DEFAULT 'N000179400' COMMENT '运费类型',
  `freight_currency` varchar(10) DEFAULT NULL COMMENT '尾程运费币种',
  `amount_freight` double(16,2) DEFAULT NULL COMMENT '尾程运费试算',
  `pre_freight_currency` varchar(10) DEFAULT NULL COMMENT '头程运费币种',
  `pre_amount_freight` double(16,2) DEFAULT NULL COMMENT '头程运费试算',
  `carry_tariff_currency` varchar(10) DEFAULT NULL COMMENT '尾程物流派送关税币种',
  `carry_tariff` double(16,2) DEFAULT NULL COMMENT '尾程物流派送关税',
  `subsidy_currency` varchar(10) DEFAULT NULL COMMENT '活动补贴币种',
  `subsidy` double(16,2) DEFAULT NULL COMMENT '活动补贴',
  `vat_fee_currency` varchar(10) DEFAULT NULL COMMENT 'VAT币种',
  `vat_fee` double(16,2) DEFAULT NULL COMMENT 'VAT费用',
  `paypal_fee_currency` varchar(10) DEFAULT NULL COMMENT '支付手续费币种',
  `paypal_fee` double(16,2) DEFAULT NULL COMMENT '支付手续费',
  `league_fee_currency` varchar(10) DEFAULT NULL COMMENT '流量活动费用币种',
  `league_fee` double(16,2) DEFAULT NULL COMMENT '流量活动费用',
  `pur_return_fee_currency` varchar(10) DEFAULT NULL COMMENT '采购返佣金币种',
  `pur_return_fee` double(16,2) DEFAULT NULL COMMENT '采购返佣金',
  `order_origin` varchar(50) DEFAULT NULL COMMENT '订单来源',
  `order_origin_version` varchar(50) DEFAULT NULL COMMENT '订单来源版本号',
  `default_warehouse` varchar(15) DEFAULT NULL COMMENT '第一次获取订单时BBC平台用户指定的仓库',
  `default_logistics_mode_id` int(11) DEFAULT NULL COMMENT '第一次获取订单时BBC平台用户指定的物流方式',
  `default_logistics_cd` varchar(15) DEFAULT NULL COMMENT '第一次获取订单时BBC平台用户指定的物流公司',
  `pay_account_id` varchar(100) DEFAULT NULL COMMENT '支付账户',
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_auto_split` varchar(2) DEFAULT NULL COMMENT '是否自动拆单,0-否,1-是',
  `is_on_sale_snapshot` varchar(2) DEFAULT NULL COMMENT '是否已上架,历史为null,0-否,1-是',
  `is_edited_snapshot` varchar(2) DEFAULT NULL COMMENT '是否编辑完整(图片价格名称)0-否1-是',
  `is_indicator_snapshot` varchar(2) DEFAULT NULL COMMENT '订单的商品是否完整被编辑,is_on_sale_snapshot&&is_edited_snapshot,0-否,1-是',
  `indicator_update_time` datetime DEFAULT NULL COMMENT 'is_indicator_snapshot的修改时间',
  `is_remote_area` tinyint(3) unsigned DEFAULT '0' COMMENT '偏远地区（默认 0 否，1 是）',
  `cancel_reason_code` varchar(20) DEFAULT NULL COMMENT '取消原因',
  `cancel_reason` varchar(255) DEFAULT NULL COMMENT '取消原因',
  `BUYER_USER_IDENTITY_NAME` varchar(100) DEFAULT NULL COMMENT '买家真实姓名',
  `insurance_currency` char(10) DEFAULT NULL COMMENT '保险币种',
  `insurance_fee` double(16,2) DEFAULT NULL COMMENT '保险费',
  `EXCEPTION_NUM` int(10) DEFAULT NULL COMMENT '记录派单失败次数',
  `is_apply_after_sale` tinyint(1) DEFAULT NULL COMMENT '是否申请过售后，1是',
  `after_sale_type` tinyint(1) DEFAULT NULL COMMENT '售后类型，1补发，2换货',
  `promo_code` char(10) DEFAULT NULL COMMENT '优惠码',
  `phone_country` varchar(8) DEFAULT NULL COMMENT '国家号',
  `phone_area` varchar(8) DEFAULT NULL COMMENT '区号',
  `out_trade_no` varchar(64) DEFAULT NULL COMMENT '我方支付请求号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID_ORDER_ID_PLAT_CD` (`ORDER_ID`,`PLAT_CD`) USING BTREE,
  UNIQUE KEY `b5c_order_no` (`B5C_ORDER_NO`) USING BTREE,
  KEY `IDX_PLAT_CD` (`PLAT_CD`) USING BTREE,
  KEY `IDX_B5C` (`B5C_ORDER_NO`) USING BTREE,
  KEY `IDX_BWC` (`BWC_ORDER_STATUS`) USING BTREE,
  KEY `IDX_STORE_ID` (`STORE_ID`) USING BTREE,
  KEY `IDX_ORDER_TIME` (`ORDER_TIME`) USING BTREE,
  KEY `ID_PARENT_ORDER_ID` (`PARENT_ORDER_ID`),
  KEY `IDX_LMI` (`logistic_model_id`),
  KEY `IDX_LSSC` (`LOGISTICS_SINGLE_STATU_CD`),
  KEY `idx_freight_type` (`freight_type`),
  KEY `idx_order_id` (`ORDER_ID`) USING BTREE,
  KEY `idx_wh` (`WAREHOUSE`) USING BTREE,
  KEY `idx_lsdc` (`LOGISTICS_SINGLE_STATU_CD`) USING BTREE,
  KEY `idx_lc` (`logistic_cd`) USING BTREE,
  KEY `idx_auci` (`ADDRESS_USER_COUNTRY_ID`) USING BTREE,
  KEY `idx_order_no` (`ORDER_NO`) USING BTREE,
  KEY `idx_op_id` (`ORDER_ID`,`PARENT_ORDER_ID`) USING BTREE,
  KEY `idx_pp_id` (`PLAT_CD`,`PARENT_ORDER_ID`),
  KEY `idx_THIRD_DELIVER_STATUS` (`THIRD_DELIVER_STATUS`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=1661539 DEFAULT CHARSET=utf8;