<?php
/**
 * b5c订单备份表
 * Created by PhpStorm.
 * User: b5m
 * Date: 2018/7/10
 * Time: 9:59
 */

class OrdBakModel extends BaseModel
{
    protected $trueTableName = 'tb_ms_ord';

    public $url = '';

    public function __construct()
    {
        parent::__construct();
        $this->url = HOST_URL_API . '/erp_order/delete.json';
    }

    /**
     * 订单数据备份
     * @param string $b5cOrderNo 订单号
     * @return null
     */
    public function backups($b5cOrderNo)
    {
        foreach ($b5cOrderNo as $key => $orderId) {
            $tmp = null;
            $tmp ['orderId']      = $orderId;
            $tmp ['operatorName'] = $_SESSION ['m_loginname'];
            $requestData [] = $tmp;
        }
        $this->setRequestData($requestData);
        $this->request();
        $this->_catchMe();
        return $this->getResponseData();
    }

    public function getName()
    {
        return $_SESSION ['m_loginname'];
    }

    public function getuId()
    {
        return $_SESSION ['userId'];
    }

    public function getTime()
    {
        return parent::getTime(); // TODO: Change the autogenerated stub
    }

    public function request()
    {
        $ret = curl_get_json($this->url, json_encode($this->getRequestData()));
        $ret = json_decode($ret, true);
        $this->setResponseData($ret);
        $this->setRequestUrl($this->url);
    }
}