--  20170905
ALTER TABLE `tb_hr_empl` ADD `IS_FILED` TINYINT( 1 ) NOT NULL DEFAULT '0' COMMENT '档案是否归档';
ALTER TABLE `tb_hr_card` ADD `IS_FILED` TINYINT( 1 ) NOT NULL DEFAULT '0' COMMENT '档案是否归档';
ALTER TABLE `tb_hr_empl` CHANGE `IS_FILED` `IS_FILED` TINYINT( 1 ) NOT NULL DEFAULT '0' COMMENT '档案是否归档(0无1是2否)';
ALTER TABLE `tb_hr_card` CHANGE `IS_FILED` `IS_FILED` TINYINT( 1 ) NOT NULL DEFAULT '0' COMMENT '档案是否归档(0无1是2否)';

